### ISSUE TITLE
What is the beginning, middle and end of the user experience

### ISSUE THREAD

**Issue by rethissunstar** [rethissunstar/BloodTale_AMurderMystery#1]
**How do we introduce the player to how to play? - tutorial?**
The player of the game needs some guidance on how to play.  either we give them an easy Demo version of the game to play or we at minimum have to take them through a user manual kind of interface.  from an experience point of view the former is better than the latter.
**What minimum steps can justify this working**
I would say 3 - 3 puzzles that the player has to solve
Where do we get the info and how would the player know the answers?
We started stating this would be a word puzzle game.  This leads to a lot of validation as opposed to button driven.  what people type and how they type it involves manipulating and validating with varied criteria of key words unless it was multiple choice.  Even then multiple choice would be better because the validation has the potential to be incorrect.
**What is the criteria for Winning**
Is it only that they survive like a five nights at freddys or that old western game where you played prospectors.  Could they possibly outlast the killer? - Not necessary just a thought.

**Comment by MarcoSaverino** [comment]
test

**Comment by rethissunstar** [comment]
we do want to have a tutorial that replicates the game. we should have the tutorial be separate from accessing the game.
there will be 3 puzzles.  One for each day.

**Background: We want this to be a historical Serial Killers**


**Landing**  : the intent is to open the landing page with a flash and some spooky music then load in the title/start button and the tutorial button.

**Beginning**
So they press start and what do they see:  ### Can we have a phone interface ### 
After they enter in some text for flavour and setting we are going to have them do a puzzle - this will be super simple to get them into the game.
They should succed and make it to day 2
What happens if they do not succeed on day 1 - lifebar that gets a negative if they get it wrong.
Is there a positive if they get it right? Could get a tool - a hint for the next day.

**Middle**

**Comment by MarcoSaverino** [comment]
Examples of clues if killer is Ted Bundy

Clue 1: Vermont Flag
Clue 2: University of Washington picture
Clue 3: Ronald Reagan

**Comment by rethissunstar** [comment]
ok I think we have this done just has to be implemented.
