### ISSUE TITLE
Find three api functionality that we can include

### ISSUE THREAD

**Issue by MVROZAY** [rethissunstar/BloodTale_AMurderMystery#10]

**Comment by rethissunstar** [comment]
any movement on this?

**Comment by rethissunstar** [comment]
https://github.com/johnnyjinjing/15-puzzle-api
https://publicapis.io/

**Comment by rethissunstar** [comment]
so the above was not awesome.  here is a 3rd party API that validates input text as not profanity.
http://www.purgomalum.com/

**Comment by rethissunstar** [comment]
This would be the thing that we want.  Creep out the user by telling them that you know their location and then using this server side API  to tell them the location they are at.

**Comment by MVROZAY** [comment]
> This would be the thing that we want. Creep out the user by telling them that you know their location and then using IPWHOIS.IO as a server side API to tell them the location they are at.

**Comment by renansm93** [comment]
Couldn't find any API to reproduce a voice but on the other hand I found the following website which converts text to speech. I think it's really cool.

https://beta.elevenlabs.io/
