### ISSUE TITLE
Add Input for the user once the clue is displayed

### ISSUE THREAD

**Issue by renansm93** [rethissunstar/BloodTale_AMurderMystery#21]

**Comment by renansm93** [comment]
Displayed  the first clue.
Now trying to display the input once the last message  is displayed.

**Comment by rethissunstar** [comment]
did you create a push?  Push the display of the first clue... each step matters.

**Comment by rethissunstar** [comment]
Closing this.  assigned the project version.  you should see it in the issues aswell.
