### ISSUE TITLE
research potential clues for ted bundy who will be our first serial killer

### ISSUE THREAD

**Issue by MarcoSaverino** [rethissunstar/BloodTale_AMurderMystery#7]

**Comment by renansm93** [comment]
Committed murders in the ’70s, when Gerald Ford and Jimmy Carter used to be the president. He/she was often regarded as charismatic.  Used to love bringing victims in his car.

Addicted to porn.

Keep the bodies inside of his/her house. The body used parts as a trophy, adding some makeup to them. Used to spend the night with the dead bodies most of the time,

Confessed to more than 30 murders of young women. People lost the number of murders that he committed. His true victim total is unknown and likely significantly higher. The first murderer was a student from the University of Washington who disappeared from her apartment. In the summer of 1974, at least seven young women were attacked in Washington.

Was arrested and jailed in [Utah] for aggravated kidnapping and attempted [criminal assault. He then became a suspect in a progressively longer list of unsolved homicides in several states. Facing murder charges in [Colorado], he engineered two dramatic escapes and committed further assaults in [Florida], including three murders, before his/her ultimate recapture in 1978. For the Florida homicides, he received three [death sentences] in two trials. He was executed at [Florida State Prison] in [Raiford] on January 24, 1989.

Attended law school in Utah, and women began disappearing there as well. The following year, he was pulled over by the police. A search of his vehicle uncovered a cache of burglary tools—a crowbar, a face mask, rope, and handcuffs. He was arrested for possession of these tools and the police began to link him to much more sinister crimes.

Most of his crimes was committed on a classic 1968 Volkswagen Beetle. The vehicle nowadays is on display at a museum. He used it to transport victims, move from state to state, and store weapons.

**Comment by rethissunstar** [comment]
@MarcoSaverino how do we want to use this?

**Comment by renansm93** [comment]
Basically,  is going to be like a conversation between the user and the serial killer. I was thinking we can use some of the sentences or facts in first person pretending that the serial killer is talking to the user.
